apiVersion: apps/v1
kind: Deployment
metadata:
  name: wepapp1-deployment
  labels:
    app: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: httpd
        image: bekdev24/myapp:prod
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webappservice1
spec:
  type: NodePort
  selector:
    app: webapp1
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp1-ingress 
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: mywebsite.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webappservice1 
          servicePort: 80